name: Build and Test

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'manual build for development'
        required: true
        default: 'manual'
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
      - '*dev'

jobs:
  build-container:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Container Build Test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: simp:test-${{ github.sha }}
